import type { ContentItem, Friend } from "./types";

export const SEED_CONTENT: ContentItem[] = [
  {
    id: "c1",
    title: "The Future of Remote Work",
    subtitle: "Analyzing the permanent shift in the global labor landscape.",
    author: "Jordan Hale",
    readTime: "7 min read",
    category: "Politics",
    tags: ["Politics", "Analysis", "Current Events"],
    image:
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&q=80",
    url: "https://example.com/remote-work",
    communityRating: 4.6,
  },
  {
    id: "c2",
    title: "Climate Policy Explained",
    subtitle: "Understanding the impact of global agreements and financial markets.",
    author: "Maya Patel",
    readTime: "9 min read",
    category: "Economics",
    tags: ["Economics", "Finance", "Markets"],
    image:
      "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80",
    url: "https://example.com/climate-policy",
    communityRating: 4.2,
  },
  {
    id: "c3",
    title: "The State of Political Discourse",
    subtitle: "Polarization, Trust, and the Path Forward",
    author: "Jordan Hale",
    readTime: "7 min read",
    category: "Politics",
    tags: ["Politics", "Culture"],
    image:
      "https://images.unsplash.com/photo-1462206092229-7d59c9861d09?w=800&q=80",
    url: "https://example.com/discourse",
    communityRating: 4.4,
  },
  {
    id: "c4",
    title: "The Rise of Digital Currencies",
    subtitle: "What Bitcoin and stablecoins change about money.",
    author: "Alex Chen",
    readTime: "6 min read",
    category: "Economics",
    tags: ["Economics", "Crypto", "Fintech"],
    image:
      "https://images.unsplash.com/photo-1621761191319-c6fb62000476?w=800&q=80",
    url: "https://example.com/digital-currencies",
    communityRating: 4.5,
  },
  {
    id: "c5",
    title: "AI and the Workforce",
    subtitle: "The automation landscape and what comes next.",
    author: "Eleanor Vance",
    readTime: "8 min read",
    category: "Science",
    tags: ["Technology", "Science"],
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
    url: "https://example.com/ai-workforce",
    communityRating: 4.3,
  },
  {
    id: "c6",
    title: "Navigating Local Policy Changes",
    subtitle: "How city halls are rewriting everyday rules.",
    author: "David Lee",
    readTime: "5 min read",
    category: "Politics",
    tags: ["Politics", "Local", "Community"],
    image:
      "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&q=80",
    url: "https://example.com/local-policy",
    communityRating: 4.1,
  },
];

export const SEED_FRIENDS: Friend[] = [
  {
    id: "f1",
    name: "Sarah Jenkins",
    handle: "sarahj",
    presence: "Active",
    avatar: "https://i.pravatar.cc/120?img=32",
    bio: "Curious reader. Always looking for the overlap.",
    sent: 12,
    read: 28,
  },
  {
    id: "f2",
    name: "Mark Thompson",
    handle: "markt",
    presence: "Away",
    avatar: "https://i.pravatar.cc/120?img=12",
    bio: "Economics first, politics second.",
    sent: 4,
    read: 11,
  },
  {
    id: "f3",
    name: "Emily Rodriguez",
    handle: "emilyr",
    presence: "Active",
    avatar: "https://i.pravatar.cc/120?img=47",
    bio: "Teacher. Wants honest media and safer streets.",
    sent: 19,
    read: 40,
  },
  {
    id: "f4",
    name: "David Lee",
    handle: "dlee",
    presence: "Offline",
    avatar: "https://i.pravatar.cc/120?img=15",
    bio: "Builder. Follows science more than slogans.",
    sent: 7,
    read: 9,
  },
  {
    id: "f5",
    name: "Chloe Davis",
    handle: "chloed",
    presence: "Active",
    avatar: "https://i.pravatar.cc/120?img=20",
    bio: "Faith, family, and free speech.",
    sent: 22,
    read: 31,
  },
  {
    id: "f6",
    name: "Eleanor Vance",
    handle: "eleanor_v",
    presence: "Active",
    avatar: "https://i.pravatar.cc/120?img=5",
    bio: "Curious mind. Reading widely across perspectives.",
    sent: 47,
    read: 123,
  },
  {
    id: "f7",
    name: "Alex Chen",
    handle: "alexchen",
    presence: "Active",
    avatar: "https://i.pravatar.cc/120?img=8",
    bio: "Tech enthusiast. Digital explorer. San Francisco, CA",
    sent: 12,
    read: 8,
  },
];

export const DEFAULT_AGREEMENTS = [
  "We want as little death and war as possible.",
  "We want our vote to be transparent and count no matter which side you are on.",
  "We do not want fraud in our government.",
  "We want our country to be safe.",
  "We want to have medical freedom.",
  "You cannot negotiate with terrorists.",
  "We want a free market, not being affected by globalists.",
  "We want a money system not captured by a few players.",
  "We want peace throughout the world.",
  "We don’t want money in politics.",
  "We want the news media to be honest.",
  "We want people who have committed crimes to be held accountable.",
];

export const DISCUSSION_QUESTIONS = [
  "What’s one specific moment, insight, or story that stuck with you the most—and why?",
  "Was there anything said that you strongly agreed or disagreed with? What was it?",
  "If you had to describe the main takeaway in one or two sentences, what would you say—and did it change or reinforce how you see the topic?",
];
